apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq-mgmt
  name: rabbitmq-mgmt
spec:
  type : NodePort
  selector:
      app: rabbitmq
  ports:
    - protocol: TCP
      name: amqp-tls
      port: 5671
    - protocol: TCP
      name: amqp
      port: 5672
    - protocol: TCP
      name: mgmt
      port: 15672